### ISSUE TITLE
Error Access

### ISSUE THREAD

**Issue by best1985no2** [idiidk/kahoot-tools#2]
Dear idiidk,

Thanks for the files, could you please help. I have the errors as below.

--------
Aloces-MBP:kahoot aloce$ npm i && node main.js
npm notice created a lockfile as package-lock.json. You should commit this file.
added 58 packages in 7.101s
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1362:19)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at Function.listen (/Users/aloce/Desktop/appsalo/kahoot/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/aloce/Desktop/appsalo/kahoot/main.js:13:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
Aloces-MBP:kahoot aloce$

**Comment by idiidk** [comment]
This is caused by Node not having access to port 80. You can try to run kahoot-tools on another port by setting the PORT environment variable; `PORT=3030 && node main.js` You can also try running node as root, but that is not recommended.

**Comment by idiidk** [comment]
#32
