### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nice6599** [idiidk/kahoot-tools#9]
I attemped to run node kahoot-tools.js 
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at Function.listen (/Users/nicco/kahoot-tools/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/nicco/kahoot-tools/kahoot-tools.js:16:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

**Comment by idiidk** [comment]
This isn`t really an issue with kahoot-tools. NodeJS doesn`t have access to ports below 1024 when not running as root. You could run Node as root or change the port in the kahoot-tools.js file.
